artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  #source_URL: https://www.kaggle.com/datasets/colearninglounge/gemstone-price-prediction
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  unzip_data_files: artifacts/data_ingestion/train.csv
  preprocessed_data_files: artifacts/data_transformation/preprocessed
  transform_data_files: artifacts/data_transformation/transformed

model_training:
  root_dir: artifacts/model_training
  model_path: artifacts/model_training/best_model.h5

model_evaluation: 
  root_dir: artifacts/model_evaluation
  metrics_path: artifacts/model_evaluation/metrics.json